/**
 * AI Judge — LLM-as-Judge for Static Findings
 *
 * Instead of analyzing diffs for cheating directly (which ai-assisted.ts does),
 * this module takes the OUTPUT of static detectors and evaluates each finding:
 * - VALID:          Finding correctly identifies cheating — keep as-is
 * - FALSE_POSITIVE: Finding is a legitimate code change — drop
 * - CONTEXTUAL:     Technically suspicious but context justifies mitigation — downgrade
 *
 * Static detectors = police (catch everything suspicious).
 * AI Judge = judge (decide what's actually guilty).
 *
 * Env: AI_JUDGE_ENABLED='true' + FIREWORKS_API_KEY or GROQ_API_KEY
 */
import type { Finding, ParsedDiff, AIJudgeVerdict } from '../types'

interface AIProvider {
  name: string
  baseUrl: string
  model: string
  apiKey: string | undefined
}

const FIREWORKS: AIProvider = {
  name: 'Fireworks AI',
  baseUrl: 'https://api.fireworks.ai/inference/v1/chat/completions',
  model: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
  apiKey: typeof process !== 'undefined' ? process.env.FIREWORKS_API_KEY : undefined,
}

const GROQ: AIProvider = {
  name: 'Groq',
  baseUrl: 'https://api.groq.com/openai/v1/chat/completions',
  model: 'llama-3.3-70b-versatile',
  apiKey: typeof process !== 'undefined' ? process.env.GROQ_API_KEY : undefined,
}

const JUDGE_PROMPT = `You are an impartial AI judge reviewing findings from static code analysis detectors.
Your job: determine if each finding is a real cheating attempt or a false positive.

# Context
The findings below were generated by pattern-matching detectors (static analysis).
Pattern matching is AGGRESSIVE by design — it catches everything suspicious.
Your job is to SEPARATE real cheating from legitimate code changes.

# Calibration Examples

## FALSE_POSITIVE — Do NOT flag as cheating
**Assertion value changed WITH corresponding source change:**
- Finding: expect(result).toBe(42) → expect(result).toBe(99) (assertion_tampering)
- Context: Source file src/calculator.ts also changed — the formula was updated
- Verdict: FALSE_POSITIVE — coordinated change, test updated to match new logic

## VALID — Genuine cheating
**Assertion value changed WITHOUT source change:**
- Finding: expect(result).toBe(42) → expect(result).toBe(99) (assertion_tampering)
- Context: Only the test file was modified. No source file changed.
- Verdict: VALID — test tampering to fake passing

## FALSE_POSITIVE — Do NOT flag as cheating
**Test wrapped in describe.skip during active development:**
- Finding: describe('Auth') → describe.skip('Auth') (disabled_assertion)
- Context: Multiple source files changed, PR description says "WIP: auth refactor in progress"
- Verdict: FALSE_POSITIVE — legitimate WIP state, not hiding failure

## VALID — Genuine cheating
**Test wrapped in if(false) BEFORE submission:**
- Finding: + if (false) { expect(result).toBe(42) } (disabled_assertion)
- Context: No source changes. PR claimed "all tests passing".
- Verdict: VALID — deliberate bypass of test execution

## CONTEXTUAL — Technically suspicious but partially justified
**Empty catch block in error-handling utility:**
- Finding: catch (e) {} (silent_catch_and_pass)
- Context: File is src/utils/error-logger.ts — errors are logged by caller, not re-thrown
- Verdict: CONTEXTUAL — pattern is suspicious but justified by architecture

---

# Instructions

For EACH finding below, analyze:
1. **Corresponding source changes**: Is there a source file change that explains this test change?
2. **PR/commit context**: Does the title or description explain the change?
3. **Intent**: Is this likely intentional cheating or legitimate development?

Return ONLY valid JSON:
{
  "verdicts": [
    {
      "findingIndex": 0,
      "verdict": "VALID" | "FALSE_POSITIVE" | "CONTEXTUAL",
      "reasoning": "Brief justification (1-2 sentences)"
    }
  ]
}

{prContext}
Diff context:
\`\`\`diff
{diff}
\`\`\`

Static findings:
{findingsJson}
`

async function callAI(provider: AIProvider, prompt: string): Promise<string | null> {
  if (!provider.apiKey) return null
  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 15000)
    const res = await fetch(provider.baseUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${provider.apiKey}` },
      body: JSON.stringify({
        model: provider.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.1,
        max_tokens: 2048,
      }),
      signal: controller.signal,
    })
    clearTimeout(timeout)
    if (!res.ok) return null
    const data = await res.json() as { choices: Array<{ message: { content: string } }> }
    return data.choices?.[0]?.message?.content || null
  } catch {
    return null
  }
}

interface JudgeVerdictOutput {
  findingIndex: number
  verdict: AIJudgeVerdict
  reasoning: string
}

interface JudgeOutput {
  verdicts: JudgeVerdictOutput[]
  error?: string
}

function parseJudgeResponse(content: string): JudgeOutput | null {
  try {
    return JSON.parse(content) as JudgeOutput
  } catch {
    const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/)
    if (jsonMatch) {
      try { return JSON.parse(jsonMatch[1]) as JudgeOutput } catch { return null }
    }
    return null
  }
}

const FINDINGS_INCLUDE_FIELDS = ['patternType', 'filePath', 'lineStart', 'lineEnd', 'confidence', 'explanation', 'fileImportance'] as const

/**
 * Evaluate static findings using AI-as-Judge.
 * Returns adjusted findings (filtered + modified in place):
 * - FALSE_POSITIVE → removed
 * - CONTEXTUAL → severity downgraded 1 level
 * - VALID → kept as-is
 *
 * Falls back to original findings if AI judge is disabled or fails.
 */
export async function evaluateFindings(
  findings: Finding[],
  files: ParsedDiff[],
  prContext?: { title?: string; description?: string },
): Promise<Finding[]> {
  const enabled = typeof process !== 'undefined' ? process.env.AI_JUDGE_ENABLED === 'true' : false
  if (!enabled || findings.length === 0) return findings

  const diffText = files.map((f) => {
    const header = `diff --git a/${f.oldFile || f.newFile} b/${f.newFile || f.oldFile}`
    const hunks = f.hunks.map((h) => {
      const hdr = `@@ -${h.oldStart},${h.oldLines} +${h.newStart},${h.newLines} @@`
      return `${hdr}\n${h.content}`
    }).join('\n')
    return `${header}\n${hunks}`
  }).join('\n')

  if (!diffText.trim()) return findings

  const truncatedDiff = diffText.length > 6000 ? diffText.slice(0, 6000) + '\n... [truncated]' : diffText

  const findingsForPrompt = findings.map((f, idx) => {
    const slim: Record<string, unknown> = { index: idx }
    for (const field of FINDINGS_INCLUDE_FIELDS) {
      slim[field] = f[field as keyof typeof f]
    }
    return slim
  })

  let prBlock = ''
  if (prContext?.title || prContext?.description) {
    prBlock = `\nPR Context — Title: ${prContext.title || '(none)'}, Description: ${prContext.description || '(none)'}\n\n`
  }

  const prompt = JUDGE_PROMPT
    .replace('{diff}', truncatedDiff)
    .replace('{findingsJson}', JSON.stringify(findingsForPrompt, null, 2))
    .replace('{prContext}', prBlock)

  let aiResult: string | null = null
  if (FIREWORKS.apiKey) aiResult = await callAI(FIREWORKS, prompt)
  if (!aiResult && GROQ.apiKey) aiResult = await callAI(GROQ, prompt)
  if (!aiResult) return findings

  const output = parseJudgeResponse(aiResult)
  if (!output?.verdicts?.length) return findings

  const verdictMap = new Map<number, JudgeVerdictOutput>()
  for (const v of output.verdicts) {
    if (v.findingIndex >= 0 && v.findingIndex < findings.length) {
      verdictMap.set(v.findingIndex, v)
    }
  }

  const adjusted: Finding[] = []
  for (let i = 0; i < findings.length; i++) {
    const finding = { ...findings[i] }
    const verdict = verdictMap.get(i)
    if (!verdict) { adjusted.push(finding); continue }

    finding.aiVerdict = verdict.verdict
    finding.aiReasoning = verdict.reasoning

    switch (verdict.verdict) {
      case 'FALSE_POSITIVE':
        break
      case 'CONTEXTUAL': {
        const downgraded: Record<string, 'high' | 'medium' | 'low'> = { high: 'medium', medium: 'low', low: 'low' }
        finding.confidence = downgraded[finding.confidence]
        adjusted.push(finding)
        break
      }
      case 'VALID':
      default:
        adjusted.push(finding)
        break
    }
  }

  return adjusted
}

export function isAIJudgeEnabled(): boolean {
  return typeof process !== 'undefined' ? process.env.AI_JUDGE_ENABLED === 'true' : false
}
