/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScanIndexRouteImport } from './routes/scan/index'
import { Route as PrScanIndexRouteImport } from './routes/pr-scan/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as BenchmarkIndexRouteImport } from './routes/benchmark/index'
import { Route as ShareIdRouteImport } from './routes/share/$id'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as AuthGithubCallbackRouteImport } from './routes/auth/github/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrScanIndexRoute = PrScanIndexRouteImport.update({
  id: '/pr-scan/',
  path: '/pr-scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkIndexRoute = BenchmarkIndexRouteImport.update({
  id: '/benchmark/',
  path: '/benchmark/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGithubCallbackRoute = AuthGithubCallbackRouteImport.update({
  id: '/auth/github/callback',
  path: '/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/scan': typeof ApiScanRoute
  '/share/$id': typeof ShareIdRoute
  '/benchmark/': typeof BenchmarkIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pr-scan/': typeof PrScanIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/scan': typeof ApiScanRoute
  '/share/$id': typeof ShareIdRoute
  '/benchmark': typeof BenchmarkIndexRoute
  '/history': typeof HistoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/pr-scan': typeof PrScanIndexRoute
  '/scan': typeof ScanIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/scan': typeof ApiScanRoute
  '/share/$id': typeof ShareIdRoute
  '/benchmark/': typeof BenchmarkIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pr-scan/': typeof PrScanIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/github/callback': typeof AuthGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/scan'
    | '/share/$id'
    | '/benchmark/'
    | '/history/'
    | '/login/'
    | '/pr-scan/'
    | '/scan/'
    | '/settings/'
    | '/auth/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/scan'
    | '/share/$id'
    | '/benchmark'
    | '/history'
    | '/login'
    | '/pr-scan'
    | '/scan'
    | '/settings'
    | '/auth/github/callback'
  id:
    | '__root__'
    | '/'
    | '/api/scan'
    | '/share/$id'
    | '/benchmark/'
    | '/history/'
    | '/login/'
    | '/pr-scan/'
    | '/scan/'
    | '/settings/'
    | '/auth/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiScanRoute: typeof ApiScanRoute
  ShareIdRoute: typeof ShareIdRoute
  BenchmarkIndexRoute: typeof BenchmarkIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PrScanIndexRoute: typeof PrScanIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AuthGithubCallbackRoute: typeof AuthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr-scan/': {
      id: '/pr-scan/'
      path: '/pr-scan'
      fullPath: '/pr-scan/'
      preLoaderRoute: typeof PrScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark/': {
      id: '/benchmark/'
      path: '/benchmark'
      fullPath: '/benchmark/'
      preLoaderRoute: typeof BenchmarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/github/callback': {
      id: '/auth/github/callback'
      path: '/auth/github/callback'
      fullPath: '/auth/github/callback'
      preLoaderRoute: typeof AuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiScanRoute: ApiScanRoute,
  ShareIdRoute: ShareIdRoute,
  BenchmarkIndexRoute: BenchmarkIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PrScanIndexRoute: PrScanIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AuthGithubCallbackRoute: AuthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
